# Generated by Django 5.2.7 on 2025-10-06 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('course', models.CharField(max_length=50)),
                ('marks', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
